# config.yaml

model:
  patch_size: 1
  image_size: 32
  use_ckpt: false
  num_tokens: 1
  num_channels: 3
  enc_dim: 768
  mask_ratio: 0.0
  ckpt: ''
  spat_spec: False

quantizer:
  quant_type: lucid
  latent_dim: 768
  codebook_size: 16384
  num_codebooks: 1
  norm_codes: true
  threshold_ema_dead_code: 32.0
  code_replacement_policy: batch_random
  sync_codebook: True
  ema_decay: 0.99
  commitment_weight: 1.0
  norm_latents: True
  kmeans_init: false

debug: False

loss:
  norm_pix_loss: False

training:
  batch_size: 1024
  epochs: 1000  # Reduced for faster testing
  accum_iter: 1
  use_ckpt: 'none'
  lr: 1.5e-3  # Adjusted for CIFAR-10
  min_lr: 0.0
  weight_decay: 0.0005
  warmup_epochs: 50
  sanity_check_frequency: 10  # Run sanity check every 1000 steps

data:
  num_workers: 10
  pin_mem: False

output:
  dir: './output_dir_cifar10'
  log_dir: './log_dir_cifar10'

system:
  seed: 42
  gpu_num: 4  # Adjust based on your system
  port: null